version: "3"
services:
  app:
    build: .
    tty: true
    #user: solr
    ports: # external:internal
      - "8080:8080"
    networks:
      - docker_web_network
    depends_on:
      - db
    restart: on-failure
    volumes: 
      - "./app:/opt/app"
  # db:
  #   image: postgres:13.13-bullseye
  #   tty: true
  #   networks:
  #     - docker_web_network
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

networks:
  docker_web_network:
    driver: bridge