version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-hello-world-app-20240124.042357
    tty: true
    ports:
      - "8080:8080"
    environment:
      - LOCAL_VOLUMN_PATH=/opt/app/
      - CONTAINER_NAME=docker-web-hello-world-app
    volumes: 
      - "__SOURCE__/opt/app/"
    # restart: on-failure
    networks:
      - docker_web_network
    # depends_on:
    #   - db
  # db:
  #   image: mongo:6.0.13-jammy
  #   tty: true
  #   networks:
  #     - my_network

networks:
  docker_web_network:
    driver: bridge