version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-hello-world-app-20240124.035042
    tty: true
    ports:
      - "8081:8081"
    environment:
      - LOCAL_VOLUMN_PATH=/opt/app/
      - CONTAINER_NAME=docker-web-hello-world-app
    volumes: 
      - "__SOURCE__/opt/app/"
    restart: on-failure
    depends_on:
      - db
    networks:
      - docker_web_network
  # db:
  #   image: mongo:6.0.13-jammy
  #   tty: true
  #   networks:
  #     - my_network

networks:
  docker_web_network:
    driver: bridge