version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-meme-pam-explorer-app-20240124.025751
    tty: true
    ports:
      - "8080:8080"
    environment:
      - LOCAL_VOLUMN_PATH=/app/
      - CONTAINER_NAME=docker-web-meme-pam-explorer-app
      - MONGO_HOST=db
    volumes: 
      - "__SOURCE__/app/"
    restart: on-failure
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: mongo:6.0.13-jammy
    tty: true
    networks:
      - my_network

networks:
  my_network:
    driver: bridge